config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.login '/login', :controller => :user_sessions, :action => :new
  map.logout '/logout', :controller => :user_sessions, :action => :destroy

  map.root :controller => :dashboards, :action => :show

  # Dashboard
  map.resource :dashboards, :only => [:show]

  # Tasks
  map.resources :tasks, :member => {
    :complete => :get,
    :regenerate => :get,
    :reuploading => :get,
    :reuploading_covers => :get
  }

  # Tools
  map.resources :macros
  map.resources :categories
  map.resources :user_files, :as => :files
  map.resources :profiles

  # Settings
  map.resource :settings, :only => [:show, :edit, :update]
  map.resources :users
  map.resources :proxies







  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/task.rb
class Task < ActiveRecord::Base

  include Workflow
  include Job::Downloading
  include Job::Extracting
  include Job::GenerationScreenList
  include Job::Rename
  include Job::Packing
  include Job::Uploading
  include Job::UploadingToMediavalise
  include Job::UploadingCovers
  include Job::UploadingScreenList

  ROOT_PATH_DOWNLOAD = Settings.root_path_download
  MAX_ACTIVE_TASK = Settings.max_active_task
  default_scope :order => "created_at DESC"



  # associations
  has_many :job_loggings, :dependent => :delete_all do
    def error
      all(:conditions => ["job not in (?) ", "error"]).last.comment
    rescue
      ""
    end
    def start_job(comment = "")
      (find_by_job(proxy_owner.reload.current_state.to_s) ||
       create(:job => proxy_owner.reload.current_state.to_s)).
        update_attributes!({:startup => Time.now.to_s(:db), :comment => comment })
    end

    def end_job(comment = "")
      (find_by_job(proxy_owner.reload.current_state.to_s) ||
       create(:job => proxy_owner.reload.current_state.to_s)).
        update_attributes!({ :stop_time => Time.now.to_s(:db), :comment => comment })
    end

  end

  belongs_to :category
  belongs_to :user
  # files

  # has_many :covers , :as => :assetable, :dependent => :destroy
  has_many :attachment_files , :as => :assetable, :dependent => :destroy, :class_name => "UserFile"
  has_many :list_screens, :dependent => :destroy
  has_many :task_covers , :dependent => :destroy

  belongs_to :screen_list_macro,     :class_name => "Macros"
  belongs_to :upload_images_profile, :class_name => "Profile"
  belongs_to :mediavalise_profile,   :class_name => "Profile"
  has_many   :downloading_files,     :dependent => :delete_all

  # validations
  validates_presence_of :name, :links
  validates_associated  :category
  validates_presence_of :password, :if => lambda{ |t| t.use_password }

  # validations переименовывание файла
  validates_presence_of  :that_rename, :if => lambda { |t| t.rename? }
  validates_presence_of  :macro_renaming, :if => lambda { |t| t.rename? }
  validates_presence_of  :rename_file_name, :if => lambda { |t| t.rename? }
  validates_inclusion_of :that_rename, :in => Common::ThatRename.valid_options, :if => lambda { |t| t.rename? }

  # validate :macro_renaming_checking
  # def macro_renaming_checking
  #   errors.add(:macro_renaming, :invalid) if rename? && !macro_renaming.split('.').all? {|x|
  #     Common::RenameMacros.list.include?(x) }
  # end

  # validations закачка файлов
  validates_presence_of :screen_list_macro_id, :if => lambda{ |t| t.screen_list? }
  validates_presence_of :upload_images_profile_id, :if => lambda{ |t| t.upload_images? }
  validates_presence_of :mediavalise_profile_id, :if => lambda{ |t| t.mediavalise? }

  validates_numericality_of :part_size, :allow_nil => true, :only_integer => true, :if => lambda{ |t| !t.part_size.blank? }


  validate :links_checking
  def links_checking
    errors.add(:links, :invalid) if extract_link.blank?
  end


  # name scope
  named_scope :active, :conditions => [" workflow_state not in(?) ", %w(completed)]
  named_scope :active_without_self, lambda { |t| {
      :conditions => [" tasks.workflow_state not in(?) and tasks.id not in (?) ", %w(completed error), t.read_attribute(:id) ]
    }}
  named_scope :completed, :conditions => [" workflow_state in (?) ", %w(completed error)]
  named_scope :filter, lambda{ |cond, argv|
    raise "Пустые параметры поиска" if cond.blank?
    { :conditions => [cond,argv] }}


  # callback

  after_create :new_task
  before_destroy :clear_task
  after_destroy :run_next_task
 # Если удаляем задача нужно удалить закачанные файлы
  def clear_task
    @path = task_path
    FileUtils.rm_rf(@path)
    log "delete task files #{@path}"
    downloading_files.each do |file|
      log "remove job aria ##{file.gid}"
      Aria2cRcp.remove(file.gid.to_s) rescue nil
    end
  end

  # После удаления если есть задача в очереди то запускаем ее
  def run_next_task
    begin
      @_task = user.tasks.queued.first
      @_task && (user.tasks.active.size < MAX_ACTIVE_TASK ) && @_task.start_downloading!
    rescue Workflow::TransitionHalted => ex
      erroneous!(ex.message)
    end
  end

  # если активнх задач нету отправляем задачу на скачивания
  def new_task
    start_job
    # active_tasks = user.tasks.active_without_self(self)
    start_downloading! if user.tasks.active_without_self(self).size < MAX_ACTIVE_TASK
  rescue Workflow::TransitionHalted => ex
    erroneous!(ex.message)
  end

  # Если задача завершаеться с ошибкой то  отправляем следующию задачу на выполнение
  def process_error
    @_task = user.tasks.queued.first
    if @task &&  user.tasks.active_without_self(self).blank?
      @_task.end_job
      @_task.start_downloading!
      sleep(1)
      @_task.start_job
    end
  end


  # средняя скорость загрузки по все файлам
  def speed
    # @_speed = read_attribute(:speed)
    # return @_speed unless  @_speed.to_i == 0
    return 0 if downloading_files.active.blank?
    (downloading_files.active.sum(:speed)/ downloading_files.active.count)/1.kilobyte
  rescue
    0
  end
  # процент скачанного объекма файлов
  def percentage
    return read_attribute(:percentage).to_i if downloading_files.active.blank?
    completed_length = downloading_files.active.map{ |x| x.completed_length.to_i }.sum
    total_length = downloading_files.active.map{ |x| x.total_length.to_i }.sum
    return 0 if total_length.to_i == 0
    (completed_length/100)/total_length.to_f
  rescue
    0
  end

  #
  # Выбирает ссылки из текста для ссылок
  def extract_link(text_links=self.links)
    !text_links.blank? ? URI.extract(text_links).uniq : false
  end

  # Добавление  обложек к задаче
  def task_covers=(attr)
    attr.each do |cover|
      task_covers.build( :cover => Cover.create!(:attachment => cover ))
    end
  end

  # Логирования выполнение работы
  def start_job(comment="")
    job_loggings.start_job(comment)
  end
  def end_job(comment="")
    job_loggings.end_job(comment)
  end


  # ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  def aria_ping?
    Aria2cRcp.ping
  end

  # ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  # Пути задачи
  # ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  def task_path
    File.join(ROOT_PATH_DOWNLOAD, user.id.to_s, self.id.to_s)
  end

  [[:downloding_path,'download'], [ :unpacked_path,'unpacked'], [:screen_list_path,'screen_list'],
   [ :packed_path,'packed'], [ :uploading_path,'uploading'] ].each do |method|
    define_method(method.first) do
      File.join(task_path, method.last)
    end
  end


  workflow do


    # ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    # Новая задач (в очереди )
    # ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    state :queued do

      event :start_downloading, :transitions_to => :downloading do
        halt!("Нет ответа от сервера закачек") unless aria_ping?
        end_job
      end
      event :erroneous, :transitions_to => :error do |*message|
        end_job(message.first)
      end


    end



    state :job_finish do


      on_entry do |prior_state, triggering_event, *event_args|
        write_attribute(:previous_state, prior_state.to_s)
        save!
        case prior_state.to_sym
        when :downloading # завершилось скачивание
          case
          when extracting_files?                                then send_later :start_extracting!
          when screen_list?                                     then send_later :start_generation!
          when rename? && that_rename[Common::ThatRename::FILE] then send_later :start_renaming!
          when create_archive?                                  then send_later :start_packing!
          else
            send_later :start_uploading!
          end

        when :extracting # завершилось распаковка
          case
          when screen_list?                                     then start_generation!
          when rename? && that_rename[Common::ThatRename::FILE] then start_renaming!
          when create_archive?                                  then start_packing!
          else
            start_uploading!
          end

        when :generation #
          case
          when rename? && that_rename[Common::ThatRename::FILE] then start_renaming!
          when create_archive?                                  then start_packing!
          else
            start_uploading!
          end

        when :renaming #
          case
          when create_archive? then start_packing!
          else
            start_uploading!
          end

        when :packing #
          start_uploading!

        when :uploading #
          start_finished!
        end
      end


      event :start_extracting, :transitions_to => :extracting
      event :start_renaming,   :transitions_to => :renaming
      event :start_generation, :transitions_to => :generation
      event :start_packing,    :transitions_to => :packing
      event :start_uploading,  :transitions_to => :uploading
      event :start_finished,   :transitions_to => :finished

    end
    # ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    # Ошибка
    # ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    state :error do
      on_entry { |prior_state, triggering_event, *event_args|
        start_job
        Notification.deliver_stopped_task(self) if user.notification_email?
      }
    end

    # ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    # Скачивание
    # ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    state :downloading do

      on_entry { |prior_state, triggering_event, *event_args|

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  inherit_resources
  defaults :resource_class => Tasks, :collection_name => 'tasks', :instance_name => 'task'
  respond_to :html
  respond_to :js, :only => [:index]

  def index
    index! do |format|
      format.html { render :action => :index }
      format.js { render :partial => "tasks", :layout => false, :object => @tasks }
    end
  end

  def show; @task = (current_user.admin? ? Task : current_user.tasks).find params[:id]  end

  def create
    if params[:task][:category_id]
    create! do |success, failure|
      session[:task_status] = "active"
      success.html { redirect_to tasks_path }
      failure.html { render :new }
    end
    else
      flash[:notice] = 'выберите категорию'
      redirect_to :back
    end
  end

  # Завершение задачи
  def complete
    @task = current_user.tasks.find params[:id]
    # Task.send_later(:comlete!, @task)
    @task.complete! if @task.finished?
    flash[:notice] = I18n.t('start_completed')
    redirect_to task_path(@task)
  end

  # Повторная генерация скрин листов
  def regenerate
    @task = current_user.tasks.find params[:id]
    @task && @task.finished? && @task.regenerate!
    flash[:notice] = I18n.t('restart_generate_screen_list')
    redirect_to task_path(@task)
  end

  # Повторная загрузка изображений
  def reuploading
    @task = current_user.tasks.find params[:id]
    @task && @task.finished? && @task.reuploading!
    flash[:notice] = I18n.t('restart_uploding_screen_list')
    redirect_to task_path(@task)
  end
  # Повторная загрузка обложек
  def reuploading_covers
    @task = current_user.tasks.find params[:id]
    @task && @task.finished? && @task.reuploading_covers!
    flash[:notice] = I18n.t('restart_uploading_covers')
    redirect_to task_path(@task)
  end

  protected
  def collection
    session[:task_status]   ||= "active"
    session[:task_category] ||= nil

    session[:task_status] = params[:status] if params[:status]

    if params[:category] && params[:category]["-1"]
      session[:task_category] = nil
    elsif  params[:category]
      session[:task_category] = params[:category]
    end

    @conditions, @arguments = [], { }
    @conditions << case session[:task_status]
                   when /active/
                     " workflow_state not in ( :completed_state ) "
                   when /completed/
                     " workflow_state in ( :completed_state ) "
                   end
    @arguments.merge!({ :completed_state => %w(completed)})
    @conditions << " category_id = :category " if session[:task_category]
    @arguments.merge!({ :category => session[:task_category]})  if session[:task_category]
    @conditions = @conditions.join(" AND ")
    @tasks = (current_user.admin? ? Task : current_user.tasks).filter(@conditions, @arguments).paginate :per_page => current_user.user_per_page, :page => params[:page]
  end

  def begin_of_association_chain
    current_user
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= error_messages_for 'task', :class => 'failure block_error', :header_message => nil, :message => nil %>

<ul class="inputForm">
  <li>
    <%= label_tag :name, I18n.t("task_name") %>
    <%= form.text_field :name, :size => "30", :id => "enterName" %>
    <div class="floatRight">
      <%= I18n.t("select_category") %>
      <%= form.select :category_id, Category.all.map{|x| [x.name, x.id]} %>
    </div>
  </li>

  <li>
    <%= form.label :description, I18n.t("description") %>
    <%= form.text_area :description, :rows => 4, :cols => 40  %>
  </li>
  <li>
    <%= form.label :links, I18n.t("add_links") %>
    <%= form.text_area :links, :rows => 4, :cols => 57, :class => "floatLeft"  %>

    <div class="passOptions">
      <%= form.check_box :use_password %><%= I18n.t("password_option") %><br/>
      <%= form.password_field :password, :disabled => true, :class => "passwdField", :size => 20 %>
    </div>
  </li>
</ul>


<h2><%= I18n.t("jobs_list") %></h2>
   <div class="jobList">
     <div class="floatLeft">
       <%= form.check_box :extracting_files %><%= I18n.t("Extracting files") %>
     </div>

     <div class="floatLeft">
       <p><%= form.check_box :rename %><%= I18n.t("Rename") %></p>
       <p class="option">
         <%  Common::ThatRename.options_for_select.each do |t| -%>
         <%= radio_button "task", "that_rename",  t.last.to_s %> <%= I18n.t(t.first) %>
         <% end -%>
       </p>
       <p class="option">
         <%= form.label :rename_file_name, I18n.t("name") %><br />
         <%= form.text_field :rename_file_name, :size => 33 %>
       </p>
       <p class="option"><%= I18n.t("text") %><br />
         <%= form.text_field :rename_text, :size => 33 %></p>
       <p class="option">
         <%= I18n.t("macro_of_file_name") %><br />
         <%= form.text_field :macro_renaming, :size => 33 %>
         <a class="infoIcon jTip" id="one" name="Macro variables" href="#" >Help</a>
         <div style="display:none" id="one_text">
           File name [file_name] <br />
           File extension [ext]
           Some text [text]
           Archive part [part_number]
         </div>
       </p>
     </div>

     <div class="floatLeft">
       <p class="screen">
         <%= form.check_box :screen_list %><%= I18n.t("Create_screen") %><br />
         <%= form.select :screen_list_macro_id, current_user.macros.map{|x| [x.name, x.id]}, :include_blank => true %>
       </p>

       <p class="upload">
         <%= form.check_box :upload_images %><%= I18n.t("upload_images") %><br />
         <%= form.select :upload_images_profile_id,
             current_user.profiles.without_mediavalise.map{|x| [x.name, x.id]}, :include_blank => true  %>
       </p>


       <p class="archive">
         <%= form.check_box :create_archive %><%= I18n.t("create_arhive") %><br />

         <p class="archiveField">
         Part size (per Mb)<br />
         <%= form.text_field :part_size, :size => 22 %><br />
         Protect by password<br />
         <%= form.text_field :password_arhive, :size => 22 %>
         </p>
       </p>

     </div>

     <div class="floatRight">
       <p class="upload2">
         <%= form.check_box :mediavalise %><%= I18n.t("upload_to_mediavalise") %><br />
         <%= form.select :mediavalise_profile_id,
             current_user.profiles.mediavalise.map{|x| [x.name, x.id]}, :include_blank => true  %>
       </p>
     </div>
   </div>



<!-- other options -->
<div class="otherOptions">
  <div class="floatLeft">
    <h2><%= I18n.t("covers") %></h2><br class="clear" />
		<div id="but_img_upload" class="floatLeft">
			<input id="File1" type="file"/>
		</div>

		<script type="text/javascript">
      window.onload = WindowOnLoad;
      var fileInput = document.getElementById('File1');
      var fileName = document.createElement('div');
      fileName.style.display = 'none';
      var activeButton = document.createElement('div');
      var bb = document.createElement('div');
      var bl = document.createElement('div');
      function WindowOnLoad()
      {
      var wrap = document.getElementById('but_img_upload');
      fileName.setAttribute('id','FileName');
      activeButton.setAttribute('id','activeBrowseButton');
      fileInput.value = '';
      fileInput.onchange = HandleChanges;
      fileInput.onmouseover = MakeActive;
      fileInput.onmouseout = UnMakeActive;
      fileInput.className = 'customFile';
      bl.className = 'blocker';
      bb.className = 'fakeButton';
      activeButton.className = 'fakeButton';
      wrap.appendChild(bb);
      wrap.appendChild(bl);

      wrap.appendChild(activeButton);

      wrap.appendChild(fileName);


      };
      function HandleChanges()
      { fileName.style.display = 'block'; };
      function MakeActive() {
           activeButton.style.display = 'block';  };
      function UnMakeActive() { activeButton.style.display = 'none';  };
    </script>


    <ul class="listFiles" id="coversFiles">
    </ul>
  </div>

  <div class="floatLeft">
    <h2><%= I18n.t("Attachments") %></h2><br class="clear" />
    <ul class="floatLeft marginRight">
      <li><%= form.check_box :add_screens_to_arhive %><%= I18n.t("add_screen_list_to_archive") %></li>
      <li><%= form.check_box :add_covers_to_arhive %><%= I18n.t("add_covers_to_archive") %></li>
    </ul>

    <a href="#" class="awesome floatLeft" rel="#addFile">Add files</a>
    <ul class="listFiles" id="attachmentFiles">
    </ul>

  </div>

  <div class="floatLeft">
    <h2><%= I18n.t("use_proxy") %></h2><br class="clear" />
    <ul class="floatLeft marginRight">
      <li>
        <%= radio_button_tag "task[proxy]", 1,  @task.proxy %>
        <%= I18n.t("yes") %>
      </li>
      <li>
        <%= radio_button_tag "task[proxy]", 1,  @task.proxy %><%= I18n.t("no") %>
      </li>
    </ul>
  </div>

</div>
                <!-- end other options -->
   <!-- ------------------------------------ -->



   <!-- overlay addfile -->
   <div class="apple_overlay"  id="addFile">
     <div class="addFileOver">
       <h1><%= I18n.t("add_files") %></h1>
       <ul>
         <% current_user.user_files.each do |ff| -%>
         <li>
           <%= check_box_tag "_task[attachment_file_ids][]", ff.id, false,
               :id => "_task_attachment_file_ids_#{ff.id}", :data_title_file => ff.title %>
           <label class="<%= cycle('yellowCell','') %>"><%= ff.title %></label>
         </li>
         <% end -%>
         <li><a href="#" class="awesome">Save</a></li>
       </ul>
     </div>
   </div>
   <!-- end overlay addfile -->





   <script type="text/javascript" charset="utf-8">
  $(function(){

    $("#File1").change(function(){
     var t = $(this).clone();
     $(t).attr({"name":"task[task_covers][]", "id":""}).css({"display":"none"});

     $("#coversFiles").append(
       $("<li class='borderNone'></li>")
          .append("<span class='listImg'>"+$(this).val()+"</span>")
          .append("<a href='#' class='smallDelBut delCoverFile' rel='#delete' title='Delete' >delete</a>")
          .append($(t))
      );
     $(this).val("");
    });

    $(".delCoverFile").live("click", function(){
       var item = $(this).parents("li:first");
       $(item).remove();
       return false;
      });

    $(".delAttachmentFile").live("click", function(){
       var item = $(this).parents("li:first");
       var i = $(item).find("input:first");
       $("#_task_attachment_file_ids_"+$(i).val()).attr("checked","");
       $(item).remove();
       return false;
      });

  	$(".awesome[rel]").overlay({effect: 'apple', expose: '#000',
        onClose: function(){
          var list_files = $("#attachmentFiles")
          $(list_files).find("li").remove();
          $.each($("#addFile").find("input:checked"),function(i,item){

          var t = $(item).clone();
          $(t).attr({"name":"task[attachment_file_ids][]", "id":""}).css({"display":"none"});
          var title_file = $(t).attr("data_title_file");
          $(list_files).append(
          $("<li class='bordernone'></li>")
                   .append("<span>"+title_file+"</span>")
                   .append("<a class='smallDelBut delAttachmentFile' href='#' rel='#delete' title='delete'>delete</a>")
                   .append($(t))
            );
           });
         },
        onBeforeLoad: function(){
          var wrap = this.getContent();
          var _close = this.getClosers();
          wrap.find('a:last').bind("click",function(){
                  $(_close).trigger("click");
                  return false;
            });
         }});

  var data ="<%= current_user.tasks.map(&:name).join(' ') %>".split(" ");
  $("#enterName").autocomplete(data);


    /* список объектов которые активируються при включение флажков   */
    var list_toggle_element = [
     {"tg_el": "#task_rename",               "ct_el": ".option"},
     {"tg_el": "#task_use_password",         "ct_el": "#task_password"},
     {"tg_el": "#task_screen_list",          "ct_el": "#task_screen_list_macro_id"},
     {"tg_el": "#task_upload_images",        "ct_el": "#task_upload_images_profile_id"},
     {"tg_el": "#task_create_archive",       "ct_el": ".archiveField"},
     {"tg_el": "#task_mediavalise",          "ct_el": "#task_mediavalise_profile_id"}
     ];

    $.each(list_toggle_element, function(i, item){


      if (!$(item["tg_el"]).attr("checked")) {
        $(item["ct_el"]).css({"color":"#666666"});
        $(item["ct_el"]).filter("input").attr("disabled", "disabled")
              .andSelf().filter("select").attr("disabled", "disabled")
              .andSelf().find("input").attr("disabled", "disabled");
       };

     $(item["tg_el"]).bind("change",function(){
       if ($(item["tg_el"]).attr("checked")) {
        $(item["tg_el"]).parents(":first").css({"color":"#000000"});
        $(item["ct_el"]).css({"color":"#000000"});

        $(item["ct_el"]).filter("input").attr("disabled", "")
                        .andSelf().filter("select").attr("disabled", "")
                        .andSelf().find("input").attr("disabled", "");

       } else {
        $(item["tg_el"]).parents(":first").css({"color":"#666666"});
        $(item["ct_el"]).css({"color":"#666666"});
        $(item["ct_el"]).filter("input").attr("disabled","disabled").attr("checked","").val("")
                        .andSelf().filter("select").attr("disabled", "disabled").val("")
                        .andSelf().find("input[type=radio]").attr("disabled", "disabled").attr("checked","")
                        .andSelf().find("input[type!=radio]").attr("disabled", "disabled").attr("checked","").val("");
       };
     })

    });
  });
</script>

app/views/tasks/_logs.html.erb
<table class="brown">
  <tr>
    <th><%= I18n.t("current_state") %></th>
    <th colspan=3><%= I18n.t  @task.state %></th>
  </tr>
  <tr>
    <th><%= I18n.t("job") %></th>
    <th><%= I18n.t("start_time") %></th>
    <th><%= I18n.t("stop_time") %></th>
    <th><%= I18n.t("comment") %></th>
  </tr>
  <% logs.each do |l| -%>
  <tr>
    <td><%= l.job %></td>
    <td><%= l.startup %></td>
    <td><%= l.stop_time %></td>
    <td><%= l.comment %></td>
  </tr>
  <% end -%>
</table>

app/views/tasks/_screen_list.html.erb
<h3>Screen list</h3>

<% screen_list.each do |sc|  %>
<div><%= link_to image_tag(sc.screen.attachment.url(:thumb)) , image_path(sc.screen.attachment.url) %></div>
<ul>
  <% sc.links && sc.links.each do |link|  %>
  <li>
    <div><%=h link.first %></div>
    <div><%= text_area_tag "", link.last , :cols => 120, :rows => 2 %></div>
  </li>
  <% end -%>
</ul>
<% end -%>

app/views/tasks/edit.html.erb
<%= head_page "edit_task" %>
<% semantic_form_for :task, @task, :url => task_path, :html => { :method => :put, :class => 'base_form' }  do |form| %>
<%= render :partial => 'form', :object => form %>
<% form.buttons do -%>
<%= form.commit_button I18n.t('save'),  :class => "base_buttons" %>
<% end -%>
<% end -%>

app/views/tasks/index.html.erb
<div class="overHidden">
<h1 class="floatLeft"><%= I18n.t(session[:task_status]["active"] ? "active_tasks" : "completed_tasks") %></h1>

<form class="categories floatRight" action="#" method="post">
<%= select_tag :category,options_for_select([[I18n.t("all_categories"),nil]]+Category.all.map{|x| [x.name, x.id]},
    session[:task_category].to_i), :class => "categories" %>
</form>
</div>
<div id="load_content">
  <%= render :partial => 'tasks', :object => @tasks %>
</div>

<script type="text/javascript" charset="utf-8">

  $(function(){
    $("#category").change(function(){
       var _url = "<%= tasks_path(:format=> :js, :category => :id)%> ";
       if ($(this).val()) { _url = _url.replace("id", $(this).val());
       } else { _url = _url.replace("id", "-1"); };
       $.ajax({ url: _url, success: function(data){ $("#load_content").html(data); } });
     });

  <% if session[:task_status]["active"] -%>
    $(document).everyTime(15000,'indicate_timer' ,function(i) {
      var _url = location.href.split('?')[0] + ".js"+(location.href.split('?')[1] ? ('?'+location.href.split('?')[1]) : '' );
       $.ajax({ url: _url, success: function(data){ $("#load_content").html(data); } });
      });
  <% end %>

   });
</script>