config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.login '/login', :controller => :user_sessions, :action => :new
  map.logout '/logout', :controller => :user_sessions, :action => :destroy

  map.root :controller => :dashboards, :action => :show

  # Dashboard
  map.resource :dashboards, :only => [:show]

  # Tasks
  map.resources :tasks, :member => {
    :complete => :get,
    :regenerate => :get,
    :reuploading => :get,
    :reuploading_covers => :get
  }

  # Tools
  map.resources :macros
  map.resources :categories
  map.resources :user_files, :as => :files
  map.resources :profiles

  # Settings
  map.resource :settings, :only => [:show, :edit, :update]
  map.resources :users
  map.resources :proxies







  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic  do |c|
    c.login_field = 'email'
  end

  acts_as_authorization_subject

  default_scope :order => "created_at DESC"

  # associations
  # задачи, если пользователя удаляют то в задача user_id == nil
  has_and_belongs_to_many :roles
  has_many :tasks, :dependent => :nullify
  has_many :proxies
  has_many :macros, :class_name => "Macros"
  has_many :user_files, :as => :assetable, :dependent => :destroy


  has_many :profiles do
    def mediavalise
      all :conditions => { :host => Common::Host::MEDIAVALISE}
    end
    def without_mediavalise
    all :conditions => [ " host not in(?) ", Common::Host::MEDIAVALISE]
    end
  end

  def admin?
    has_role? :admin
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  inherit_resources
  defaults :resource_class => User,
           :collection_name => 'users', :instance_name => 'user'
  respond_to :html, :js

  access_control do
    allow :admin
  end


  def new
    new! do |format|
      format.html { render :action => :new }
      format.js   { render :action => :new, :layout => false }
    end
  end

  def create
    create! do |success, failure|
      success.html { redirect_to users_path }
      failure.html {
        flash[:error] = resource.errors.full_messages.join(', ')
        render :action => "new"
      }
    end
  end
  def edit
    edit! do |format|
      format.html { render :action => :edit }
      format.js   { render :action => :edit, :layout => false }
    end
  end

  def update
    update! do |success, failure|
      success.html { redirect_to users_path }
      failure.html {
        flash[:error] = resource.errors.full_messages.join(', ')
        render :action => "edit"
      }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<li><label><%= I18n.t("nickname") %></label><em class="rightCell"></em>
  <%= form.text_field :name, :size => 20 %>
</li>
<li><label class="yellowCell">E-mail</label><em class="rightCell"></em>
  <%= form.text_field :email, :size => 19 %>
</li>
<li><label><%= I18n.t("password") %></label><em class="rightCell"></em>
  <%= form.password_field :password, :size => 19 %>
</li>
<li><label class="yellowCell"><%= I18n.t("repeat_password") %></label><em class="rightCell"></em>
  <%= form.password_field :password_confirmation, :size => 19 %>
</li>
<li>
  <label class="borderNone"><%= I18n.t("account_type") %></label>
  <em class="rightCell"></em>
  <% if resource.new_record? -%>
    <%= select_tag  "user[role_ids][]",
      options_for_select(Role.all.map{|x| [x.name, x.id]} ),
      { :include_blank => I18n.t("Choose account type")} %>
  <% else -%>
  <%= select_tag  "user[role_ids][]",
      options_for_select(Role.all.map{|x| [x.name, x.id]}, resource.roles.first.id ),
      { :include_blank => I18n.t("Choose account type")} %>
  <% end -%>
</li>

app/views/users/edit.html.erb
<h1>
  <%=  I18n.t("edit_user") %>: <span class="finished">[<%= resource.email %>]</span>
</h1>

<% form_for @user, :url => user_path, :html => { :method => :put}  do |form| %>
<ul class="tableForm toolsProfiles">
  <%= render :partial => 'form', :object => form %>
  <li class="borderNone">
    <%= submit_tag I18n.t("Save"), :class => "awesome borderNone" %>
  </li>
</ul>
<% end -%>

app/views/users/index.html.erb
<div class="overHidden">
  <h1 class="floatLeft"><%= I18n.t("users") %></h1>
  <%= link_to I18n.t("add_user"), new_user_path, :class => "awesome floatRight js_link", :rel => "#addUser" %>
</div>

<table class="brown">
  <tr class="tableTitle">
    <td><%= I18n.t("login") %></td>
    <td><%= I18n.t("added_date") %></td>
    <td><%= I18n.t("tasks") %></td>
    <td><%= I18n.t("actions") %></td>
  </tr>
  <% @users.each do |user| -%>
  <tr class="<%= cycle('yellowCell','') %>">
    <td><%= user.email %></td>
    <td><%= user.created_at.strftime("%d.%m.%Y %H:%M") %></td>
    <td><span class="finished"><%= user.active_tasks.to_i %>/<%= user.completed_tasks.to_i %></span></td>
    <td>
      <%= link_to I18n.t("edit"), edit_user_path(user), :class => "editBut js_link", :rel => "#editUser"  -%>
      <%= link_to I18n.t("delete"), "", :title => I18n.t("delete_user"), :rel => "#delete", :class=>"delBut" %>
      <div style="display:none">
        <p>Are you sure you want to delete?<br /><%= user.name || user.email %></p>
        <div class="buttonBlock">
          <%= link_to I18n.t("yes"),  user_path(user), :method => :delete, :class => "awesome floatLeft" %>
          <a href="#" class="awesome floatRight">No</a>
        </div>
      </div>
    </td>
  </tr>
  <% end -%>
</table>

<% content_for :overlay do -%>
<div class="apple_overlay" id="addUser">
  <div class="addUserOver">
</div></div>
<div class="apple_overlay" id="editUser">
  <div class="addUserOver">
</div></div>
<div class="apple_overlay"  id="delete">
  <div class="delOver">
</div></div>
<% end -%>

<script type="text/javascript" charset="utf-8">

  $(function(){

  $(".delBut[rel]").overlay({effect: 'apple', expose: '#000',
     onBeforeLoad: function() {
      var wrap = this.getContent().find(".delOver");
        wrap.html(this.getTrigger().next("div").clone().html());
      var _close = this.getClosers();
        wrap.find("a:last").bind("click",function(){ $(_close).trigger("click"); });
    }
  });


  $(".js_link[rel]").overlay({
   expose: '#000',
   effect: 'apple',
   onBeforeLoad: function() {
       var wrap = this.getContent().find(".addUserOver");
      if  (this.getTrigger().hasClass("editBut")){
         wrap.addClass("editUser");
       } else {
         wrap.removeClass("editUser");
        };
       wrap.load((this.getTrigger().attr("href")+".js"));
      }
  });

  });
</script>

app/views/users/new.html.erb
<%= content_tag :h1, I18n.t("add_user") %>
<% form_for @user,:url => users_path,  :html => { :method => :post }  do |form| %>
<ul class="tableForm toolsProfiles">
  <%= render :partial => 'form', :object => form %>
  <li class="borderNone">
    <%= submit_tag I18n.t("Save"), :class => "awesome borderNone" %>
  </li>
</ul>
<% end -%>